name: RLlib EnergyPlus Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  unit-tests:
    name: Test RLlib EnergyPlus
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install keyring keyrings.alt
          pip install -r requirements.txt

      - name: Install EnergyPlus
        run: |
          ENERGYPLUS_VERSION="23.2.0"
          ENERGYPLUS_SHA="7636e6b3e9"
          ENERGYPLUS_DOWNLOAD_URL ="https://github.com/NREL/EnergyPlus/releases/download/v${ENERGYPLUS_VERSION}/EnergyPlus-${ENERGYPLUS_VERSION}-${ENERGYPLUS_SHA}-Linux-Ubuntu22.04-x86_64.sh"
          wget --quiet "${ENERGYPLUS_DOWNLOAD_URL}" -O /tmp/eplus_install.sh
          (echo "y"; echo ""; echo "y";) | sudo bash /tmp/eplus_install.sh

      - name: Execute tests
        env:
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
          PYTHONPATH: "/usr/local/EnergyPlus-23-2-0/:.:$PYTHONPATH"
        run: |
          python tests/__init__.py